# Generated by Django 5.0.6 on 2024-07-01 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0002_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='context',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.TextField(default='[]'),
        ),
    ]
