# Generated by Django 5.0.6 on 2024-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0006_conversation_messages_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.TextField(default=[]),
        ),
    ]
