# Generated by Django 5.0.6 on 2024-07-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0007_alter_conversation_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Conversations',
        ),
    ]
