# Generated by Django 5.0.6 on 2024-07-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0008_rename_conversation_conversations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
    ]
