# Generated by Django 5.0.6 on 2024-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0009_rename_conversations_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
