# Generated by Django 5.0.6 on 2024-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0010_alter_conversation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sentiment',
            field=models.TextField(null=True),
        ),
    ]
