# Generated by Django 5.0.6 on 2024-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingbong_devapp', '0011_conversation_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
